### ISSUE TITLE
What's Greg's full name?

### ISSUE THREAD

**Issue by kahdojay** [fdel15/whiteboardingWednesdays#1]
@fdel15 what's Greg's full name? Also do you still have the link that he provided on the ppt printout that he provided at the workshop?

**Comment by fdel15** [comment]
Gregory Marton

https://bitbucket.org/gregory_marton/coding-interview/src

Also, I started organizing White Board Wednesdays. We had our first meeting
tonight. They are more structured now. Check out the repo
https://github.com/fdel15/whiteboardingWednesdays and let me know what
you think.

Thanks,

--Frank

**Comment by kahdojay** [comment]
@fdel15 thanks! Looks well structured, sorry I didn't make it yesterday. I'll be in DC next week so won't make that one, but will definitely try to make it thereafter. Quick feedback is to try to do more problems while minimally sacrificing depth.
